version: '3.8'
services:
  frontend:
   web:
    image: 14luxoo/tienda-frontend:latest
    build: ./fronted
    ports:
      - "3000:3000"
    restart: always
  backend:
    image: 14luxoo/tienda-backend:latest
    build: ./backend
    ports: 
      - "3001:3001"
    restart: always
  db:
    image: 14luxoo/tienda-db:latest
    build: ./backend
    ports: 
      - "3306:3306"
    restart: always 
